import React from 'react'
import Image from 'next/image'
import Head from 'next/head';
import {Navbar, Container,NavDropdown,Nav,Form,FormControl,Button} from 'react-bootstrap'
import styles from '../styles/Navbar.module.css';

const AllNavbar = () => {
  return (
    <>
     <Head>
        <title>BitApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/BitApp.png" />
      </Head>
   <Navbar bg="light" expand="lg">
  <Container>
    <Navbar.Brand href="#" style={{marginRight:"5rem"}}>Bit<span className={styles.appFont}>App</span></Navbar.Brand>
    <Navbar.Toggle aria-controls="navbarScroll" />
    <Navbar.Collapse id="navbarScroll">
      <Nav
        className="me-auto my-2 my-lg-0"
        style={{ maxHeight: '100px' }}
        navbarScroll
      >
        <Nav.Link href="/academics"><img src="/assets/img/academics-icon.png" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/explore"><img src="/assets/img/explore-icon.png" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/maps"><img src="/assets/img/map-icon.png" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/clubactivities"><img src="/assets/img/activities-icon.png" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/files"><img src="/assets/img/files-icon.png" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/mails"><img src="/assets/img/mails.png" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/chats"><img src="/assets/img/chats-icon.png" className={styles.navbarIcons}/></Nav.Link>
    
      </Nav>
      <Form className="d-flex">
        <div><Button className={styles.profileButtons}>Profile</Button></div>
        <div><Button className={styles.profileButtons}>Edit Profile</Button></div>
        <div><Button className={styles.profileButtons}>Log Out</Button></div>
      </Form>
    </Navbar.Collapse>
  </Container>
</Navbar>

    </>
  )
}

export default AllNavbar