import React from 'react'
import Image from 'next/image'
import Head from 'next/head';
import {Navbar, Container,NavDropdown,Nav,Form,FormControl,Button} from 'react-bootstrap'
import styles from '../styles/Navbar.module.css';

const AllNavbar = () => {
  return (
    <>
     <Head>
        <title>BitApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/BitApp.png" />
      </Head>
      <Container fluid bg="light" style={{position:"fixed",zIndex:"4",marginBottom:"100px"}} >
   <Navbar bg="light" expand="lg" className={styles.navbar} >
    <Container>
    <Navbar.Brand href="/" style={{marginRight:"5rem",fontFamily: "'Kdam Thmor Pro', sans-serif"}}>Bit<span className={styles.appFont}>App</span></Navbar.Brand>
    <Navbar.Toggle aria-controls="navbarScroll" />
    <Navbar.Collapse id="navbarScroll">
      <Nav
        className="me-auto my-2 my-lg-0"
        style={{ maxHeight: '100px' }}
        navbarScroll
      >
        <Nav.Link href="/academics" style={{position:"relative",width:"2rem",height:"2rem"}} className={styles.navlink}><Image src="/assets/img/academics-icon.png" alt='Academics' layout="fill" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/explore" style={{position:"relative",width:"2rem",height:"2rem"}}  className={styles.navlink}><Image src="/assets/img/explore-icon.png" alt='Explore' layout="fill" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/maps" style={{position:"relative",width:"2rem",height:"2rem"}}  className={styles.navlink}><Image src="/assets/img/map-icon.png" alt='Maps' layout="fill" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/clubactivities" style={{position:"relative",width:"2rem",height:"2rem"}}  className={styles.navlink}><Image src="/assets/img/activities-icon.png" alt='ClubActivities' layout="fill" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/files" style={{position:"relative",width:"2rem",height:"2rem"}}  className={styles.navlink}><Image src="/assets/img/files-icon.png" alt='Files' layout="fill" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/mails" style={{position:"relative",width:"2rem",height:"2rem"}}  className={styles.navlink}><Image src="/assets/img/mails.png" alt='Mails' layout="fill" className={styles.navbarIcons}/></Nav.Link>
        <Nav.Link href="/chats" style={{position:"relative",width:"2rem",height:"2rem"}}  className={styles.navlink}><Image src="/assets/img/chats-icon.png" alt='Chats' layout="fill" className={styles.navbarIcons}/></Nav.Link>
    
      </Nav>
      <Form className="d-flex">
        <div><Button className={styles.profileButtons}>Profile</Button></div>
        <div><Button className={styles.profileButtons}>Edit Profile</Button></div>
        <div><Button className={styles.profileButtons}>Log Out</Button></div>
      </Form>
    </Navbar.Collapse>
    </Container>
</Navbar>
</Container>

    </>
  )
}

export default AllNavbar