import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import login from './login'

export default function Home() {
  return (
    <div>
      <Head>
        <title>BitApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/BitApp.png" />
      </Head>
      
    <div className="back-to-top"></div>
        <nav className="navbar navbar-expand-lg navbar-light navbar-float">
            <div className="container">
                <Link href="/login" className="navbar-brand" ><a>Bit<span className="text-primary">App</span></a></Link>
                <button className="navbar-toggler" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
        <div className="page-banner home-banner">
            <div className="container h-100">
                <div className="row align-items-center h-100">
                    <div className="col-lg-6 py-3 wow fadeInUp">
                        <h1 className="mb-4">Great Companies are built on great Products</h1>
                        <p className="text-lg mb-5">Ignite the most powerfull growth engine you have ever built for your company</p>
                        <a href="/login" className="btn btn-primary btn-split ml-2">Log In <div className="fab"><span className="mai-play"></span></div></a>
                        {" "}<a href="/auth/google" className="btn btn-primary btn-split ml-2">Sign Up With Google<div className="fab"><span className="mai-play"></span></div></a>
                        <hr/>
                        <a href="/clublogin" className="btn btn-primary btn-split ml-2">Login As Club <div className="fab"><span className="mai-play"></span></div></a>
                    </div>
                   
                    
                    <div className="col-lg-6 col-6 py-3 wow zoomIn">
                        <div className="img-place">
                            <Image src="/assets/img/bg_image_1.png" width="10" height="10" layout='responsive' priority="true"  alt=""/>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
  )
}
